<?php
declare(strict_types=1);
require_once __DIR__ . '/legal_page.php';

renderLegalPage('Privacy Policy', '
<p>PolyGo+ is a campus marketplace. This policy explains the information used to operate the service.</p>
<h2>Information we process</h2>
<p>Account and verification details; profile information; listings, messages, offers, reviews and reports; optional meetup location and timetable entries; device details submitted with bug reports; and technical data generated by Firebase Analytics, Crashlytics, Cloud Messaging and App Check.</p>
<h2>Why we use it</h2>
<p>We use this information to authenticate students, operate marketplace and safety features, moderate abuse, send requested notifications, diagnose failures and measure service reliability. We do not sell personal information.</p>
<h2>Storage and sharing</h2>
<p>Marketplace data is stored by the PolyGo+ backend. Firebase services process push-notification, integrity, analytics and crash data under their service terms. Information may be disclosed when required by law or to protect users and the service.</p>
<h2>Your choices</h2>
<p>You can make your profile private, export your data, and delete your account from the app. Deleting an account removes its profile and associated marketplace data, subject to any retention required by law, security, fraud prevention or dispute handling.</p>
<h2>Contact</h2>
<p>For a privacy request, contact <a href="mailto:support@poliku.com">support@poliku.com</a>.</p>');
